version: '2.1'
services:
  db:
    image: postgres
    ports:
      - "5432"

  redis:
    image: redis
    ports:
      - "6379"

  python:
    build: .
    command: /bin/true
    volumes:
      - .:/src
    environment:
      DEBUG: 'True'
      NODE_ENV: 'development'
      PORT: 5000
      DB_DISABLE_SSL: 'True'
      DOCKER_HOST: ${DOCKER_HOST:-missing}
      REDIS_URL: redis://redis:6379/0
      DOCKER_HOST: ${DOCKER_HOST:-missing}
    env_file: .env


  web:
    image: calichat_python
    extends:
      service: python
    command: >
      /bin/bash -c '
      sleep 3 &&
      uwsgi uwsgi.ini'
    ports:
      - "5000:5000"
    links:
      - db
      - redis

