version: '2.1'
services:
  db:
    image: postgres
    ports:
      - "5432"

  redis:
    image: redis
    ports:
      - "6379"

  nginx:
    image: diatigrah/nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/web.conf
      - ./:/src
    environment:
      - NGINX_HOST=calichat.local
      - NGINX_PORT=5000
    ports:
      - "5000:5000"
    links:
      - web1
      - web2

  python:
    build: .
    command: /bin/true
    volumes:
      - .:/src
    environment:
      NODE_ENV: 'development'
      DATABASE_URL: postgres://postgres@db:5432/postgres
      REDIS_URL: redis://redis:6379/0
      FLASK_APP: calichat/calichat.py
      FLASK_DEBUG: 1
    env_file: .env

  web1:
    image: calichat_python
    extends:
      service: python
    environment:
      PORT: 5001
    command: >
      /bin/bash -c '
      sleep 3 &&
      uwsgi uwsgi.ini'
    ports:
      - "5001:5001"
    links:
      - db
      - redis
      
  web2:
    image: calichat_python
    extends:
      service: python
    environment:
      PORT: 5002
    command: >
      /bin/bash -c '
      sleep 3 &&
      uwsgi uwsgi.ini'
    ports:
      - "5002:5002"
    links:
      - db
      - redis
