version: '2.1'
services:
  db:
    image: postgres
    ports:
      - "5432"

  redis:
    image: redis
    ports:
      - "6379"

  web:
    build: .
    command: >
      /bin/bash -c '
      sleep 3 &&
      uwsgi uwsgi.ini'
    ports:
      - "5000:5000"
    volumes:
      - .:/src
    environment:
      DEBUG: 'True'
      NODE_ENV: 'development'
      PORT: 5000
      DATABASE_URL: postgres://postgres@db:5432/postgres
      DOCKER_HOST: ${DOCKER_HOST:-missing}
      REDIS_URL: redis://redis:6379/0
      FLASK_APP: calichat/calichat.py
      FLASK_DEBUG: 1
    env_file: .env
    links:
      - db
      - redis

